# Site settings
title:              Veronica Medrano
email:              veronicanoel12490@gmail.com
description:        "Project Portfolio"
url:                "http://vnoelifant.github.io"
baseurl:            ""

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
