# Site settings
title:              Veronica Medrano
email:              your-email@domain.com
description:        "Project Portfolio"
url:                "http://vnoelifant.github.io" 
baseurl:            /vnoelifant.github.io

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
